"use client";

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/header/header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <div className='md:container md:mx-auto'>
        {children}
    </div>
  )
}
